### ISSUE TITLE
Medidas do Produto e simulação com contrato

### ISSUE THREAD

**Issue by felipe152** [luizbills/woocommerce-correios-calculator#1]
Olá, parabéns pelo projeto!
Estou testando a sua solução e reparei algumas coisas:
Os codigos para simulação com contrato é : PAC 41068 e Sedex 40096
Vi que ainda não pega as dimensões do produto, isso será colocado?

Obrigado

**Comment by luizbills** [comment]
Então, eu fiz essa calculadora inicialmente apenas para suprir a falta da calculadora que tinha antigamente. Não penso em deixar ela mais do que já está. Talvez no máximo adicionar as medidas dos produtos. Meu plano mesmo é fazer uma calculadora que já seja integrada com as areas de entrega da loja, mas para isso preciso reservar um tempinho.

**Comment by felipe152** [comment]
Realmente esta com uma falta danada dessa funcionalidade depois que retiraram do outro plugin.
Eu nunca contribui com projetos no git, vou estudar como faço isso e tentar te ajudar desde que mantenha o plugin grátis.

Em testes, eu não entendi o por que mas esta com uma diferença de valor quando comparado ao do carrinho.

**Comment by luizbills** [comment]
Acho que essa diferença deve ser por causa de peso , quantidades ou dimensões.

E o plugin vai ser sempre gatuito sim, só não coloquei no repositório do wordpress por que está meio avacalhado ainda.
