### ISSUE TITLE
Valores diferentes

### ISSUE THREAD

**Issue by lucassardelari** [luizbills/woocommerce-correios-calculator#2]
Primeiramente parabéns por suprir nossa necessidade da falta de calculadora na pagina do produto! Ficou sensacional este plugin.
Mas notei uma diferença no calculo do produto, quando eu faço a cotação pela sua calculadora da um valor, e quando a pessoa faz o calculo na finalização do produto da um valor um pouco mais alto.
Sera algo que configurei errado, ou seria mesmo da calculadora? 
Obrigado.

**Comment by lucassardelari** [comment]
Achei o erro, estava colocando uma opção de seguro no plugin dos correios.

**Comment by luizbills** [comment]
Mas muitas vezes pode dar um valor diferente mesmo. Esse plugin está somente com o "básico". Ele não está pegando medidas e peso do produto, então pode haver diferença mesmo. Se quiser implementar esses detalhes, fique a vontade :+1:

**Comment by lucassardelari** [comment]
Beleza Luiz nao manjo muito de editar plugin, mais caso eu mexer te dou um toque, e obrigado!
