### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by SANTORNET** [luizbills/woocommerce-correios-calculator#4]
Ola, primeiramente parabéns pelo trabalho, procurei muito para encontrar esta solução, fiz toda integração porem quando digito um CEP da este erro

Erro ao calcular o "PAC":
Erro ao calcular o "SEDEX":
 você pode me ajudar? alem do passo a passo que você descreveu para fazer a integração tem que fazer mais alguma configuração no código?

**Comment by luizbills** [comment]
Só tem que colocar aquele código que está no README mesmo. Porém se o seu arquivo `functions.php` estava vazio coloque ou tinha um `?>`, coloque um `<?php` antes. Também verifique se o seu servidor tem o módulo `curl`.

**Comment by luizbills** [comment]
Você pode usar esse plugin também, é uma solução mais robusta e estável: https://fernandoacosta.net/blog/2016/12/19/simulador-de-frete-dos-correios-para-woocommerce/

**Comment by SANTORNET** [comment]
Bom dia agradeço pelo retorno, era problema no servidor, já conseguir esta funcionando BLZ, obg por esta contribuição.
